### ISSUE TITLE
One Error in dot.ts

### ISSUE THREAD

**Issue by FormerBuckeye** [mariusschulz/styx#2]
Hi @mariusschulz,

I found one error in src/exporters/dot.ts: 
https://github.com/mariusschulz/styx/blob/834196806cdf764bdd9955d99631b8a6108e3e30/src/exporters/dot.ts#L11

It should be:
`import { partition } from "../util/arrayUtil";`

Thanks!~

**Comment by mariusschulz** [comment]
Thanks for pointing this out! Fixed in https://github.com/mariusschulz/styx/commit/b2d4ec6f94983ff2d85f5babb615d53872532d54, along with `--forceConsistentCasingInFileNames`.
